### PR TITLE
Add message signing and verification

### PR DESCRIPTION
**Pull request by vierbergenlars**
I think signing and verifying messages is a handy extra for this library.

Sorry for spamming you with pull requests, but I am actively using this library, and I'll add things when I need them.
Please don't look at it as if I am forcing you in this direction, just some feedback from a developer you made very happy!

### CODE REVIEW

**Comment by Cosmicist** [comment]
Hi @vierbergenlars! Glad to know you like it!

Contributions are more than welcome, and I really like this idea.

I'm not using this library that much anymore, since the system that was using it became deprecated (it was using an old version, but it was very similar) so it's great to get contributions from someone who's actively using it!

**Comment by Cosmicist** [comment]
@vierbergenlars just wanted to let you know that I updated the version to 0.1.1 to include your changes.
I completely forgot doing this at the time, but better late than never.

Thanks again for your contributions!

**Comment by vierbergenlars** [comment]
@xFlatlinex Oh, right! You're welcome!

I don't know whether you follow [semantic versioning](http://semver.org/) for your projects or not but I'll mention it anyways.
- Major version numbers are for breaking changes (removal or renaming of functions/classes)
- Minor version numbers are for non-breaking changes (addition of functions/classes)
- Patch releases are for bug fixes only (no adding/removing of functionality)

So technically this would be version 0.2.0 if you follow the semantic versioning principles
Things are a little different for 0.x.y releases. From the faq:

```
How should I deal with revisions in the 0.y.z initial development phase?

The simplest thing to do is start your initial development release at 0.1.0
and then increment the minor version for each subsequent release.
```

But of course, It's just a suggestion :wink:

**Comment by Cosmicist** [comment]
@vierbergenlars I knew about it, but had never read it carefully. I guess I will now :grinning:
Anyway, it sounds logical, and anything that's a community accepted standard is welcome, so I guess I'll re-tag the version.
I was also thinking in styling the code to further comply with psr-1 and 2.

Thanks!

**Pull request merged**
